# enable / disable logger
logging : false

# show stacktrace on error
stacktrace : true

# agent print call will be shown
agentprint : false

# enable / disable status line
statusvisible : true



# number of simulation steps - optional if not set, Integer.Max_Value is used
#steps : 2000

# thread-sleep (in milliseconds) time to slow down the simulation speed
threadsleeptime : 0



# screen size of the window - optional with default 800x600
# zoom speed for zoom sensitivity
# drag speed for dragging sensitive in 1/1000
window :
    weight    : 1800
    height    : 1200
    zoomspeed : 5
    dragspeed : 100

# creates on each definied simulation step a screenshoot - optional
# {0} is replaced by the iteration number, see Java MessageFormat (https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html),
# the number format can be defined by Java String Formatter (https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html)
screenshot :
    step   : -1
    format : "%08d"
    file   : "image{0}"



# environment (grid) resolution - required
environment :
    cellsize : 20
    rows     : 250
    columns  : 250
    routing  : "jpsplus"



# agent definition
agent :

    # agent name, asl represent the name of the agent program (relative to this configuration file), pokemon sets the name, icon and preferences
    # of the agent:

    # abra, aerodactyl, articuno, bellsprout, bulbasaur, caterpie, chansey, charmander, clefairy, cubone, diglett, ditto, doduo, dratini,
    # drowzee, eevee, ekans, electabuzz, exeggcute, farfetchd, gastly, geodude, goldeen, grimer, growlithe, hitmonchan, hitmonlee, horsea, jigglypuff, jynx,
    # kabuto, kangaskhan, koffing, krabby,lapras, lickitung, machop,magikarp, magnemite, magmar, mankey, meowth, mew, mewtwo, moltres, mr_mime, nidoran_female,
    # nidoran_male, oddish, omanyte, onix, paras, pidgey, pikachu, pinsir, poliwag, ponyta, porygon, psyduck, rattata, rhyhorn, sandshrew, scyther, seel,
    # shellder, slowpoke, snorlax, spearow, squirtle, staryu, tangela, tauros, tentacool, venonat, voltorb, vulpix,weedle, zapdos, zubat

    # number the generated elements and force the force definition

    gastly :
        number  : 500
        pokemon : "gastly"
        force   : "sum"
        asl     : "agent.asl"

    caterpie :
        number  : 500
        pokemon : "caterpie"
        force   : "sum"
        asl     : "agent.asl"

    koffing :
        number  : 500
        pokemon : "koffing"
        force   : "sum"
        asl     : "agent.asl"



# static environment (optional) elements - position is defined in (y/x) structure
element :

    - static :
        left  : [ 30, 10 ]
        right : [ 60, 20 ]
        color : "ffaa00"

    - static :
        left  : [ 60, 60 ]
        right : [ 75, 95 ]
        color : "ffbb00"

    - static :
        left  : [ 90, 100 ]
        right : [ 110, 120 ]
        color : "ffcc00"

    - static :
        left  : [ 140, 20 ]
        right : [ 100, 90 ]
        color : "ffdd00"

    - static :
        left  : [ 200, 40 ]
        right : [ 230, 120 ]
        color : "ffee00"

    - static :
        left  : [ 210, 160 ]
        right : [ 225, 240 ]
        color : "ffff00"

    - static :
        left  : [ 100, 150 ]
        right : [ 160, 210 ]
        color : "ffffaa"

    - static :
        left  : [ 10, 130 ]
        right : [ 80, 190 ]
        color : "ffffbb"
