# enable / disable logger
#logging : true

# number of simulation steps - optional if not set, Integer.Max_Value is used
#steps : 2000


# screen size of the window - optional with default 800x600
# zoom speed for zoom sensitivity
# drag speed for dragging sensitive in 1/1000
window :
    weight    : 1250
    height    : 1250
    zoomspeed : 5
    dragspeed : 100

# creates on each definied simulation step a screenshoot - optional
# {0} is replaced by the iteration number, see Java MessageFormat (https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html),
# the number format can be defined by Java String Formatter (https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html)
screenshot :
    step   : -1
    format : "%08d"
    file   : "image{0}"


# environment (grid) resolution - required
environment :
    cellsize : 25
    rows     : 500
    columns  : 500
    routing  : "jpsplus"


# agent definition - optional
agent :

    # agent name, which will be expanded on the item number,
    # number of generated agents, color for visualzation
    # type of the agent and individual preferences
    test1 :
        number : 150
        color  : "ff0000"
        force  : "sum"
        asl    : "agent.asl"

    test2 :
        number : 150
        color  : "00ff00"
        force  : "sum"
        asl    : "agent.asl"

    test3 :
        number : 150
        color  : "0000ff"
        force  : "sum"
        asl    : "agent.asl"



# static environment elements - optional
element :
    - not exists
