# enable / disable logger
logging : false

# enable / disable status line
statusvisible : true

# number of simulation steps - optional if not set, Integer.Max_Value is used
#steps : 2000

# agent print call will be shown
agentprint : false

# thread-sleep (in milliseconds) time to slow down the simulation speed
threadsleeptime : 100

# screen size of the window - optional with default 800x600
# zoom speed for zoom sensitivity
# drag speed for dragging sensitive in 1/1000
window :
    weight    : 1800
    height    : 1200
    zoomspeed : 5
    dragspeed : 100

# creates on each definied simulation step a screenshoot - optional
# {0} is replaced by the iteration number, see Java MessageFormat (https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html),
# the number format can be defined by Java String Formatter (https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html)
screenshot :
    step   : -1
    format : "%08d"
    file   : "image{0}"


# environment (grid) resolution - required
environment :
    cellsize : 20
    rows     : 250
    columns  : 250
    routing  : "jpsplus"


# agent definition
agent :

    # agent name, which will be expanded on the item number e.g. test1-0, test1-1, ...
    test1 :
        number  : 200
        pokemon : "gastly"
        force   : "sum"
        asl     : "agent.asl"

    test2 :
        number  : 200
        pokemon : "caterpie"
        force   : "sum"
        asl     : "agent.asl"

    test3 :
        number  : 200
        pokemon : "koffing"
        force   : "sum"
        asl     : "agent.asl"



# static environment (optional) elements - position is defined in (y/x) structure
element :

    - static :
        left  : [ 30, 10 ]
        right : [ 60, 20 ]
        color : "ffaa00"

    - static :
        left  : [ 60, 60 ]
        right : [ 75, 95 ]
        color : "ffbb00"

    - static :
        left  : [ 90, 100 ]
        right : [ 110, 120 ]
        color : "ffcc00"

    - static :
        left  : [ 140, 20 ]
        right : [ 100, 90 ]
        color : "ffdd00"

    - static :
        left  : [ 200, 40 ]
        right : [ 230, 120 ]
        color : "ffee00"

    - static :
        left  : [ 210, 160 ]
        right : [ 225, 240 ]
        color : "ffff00"

    - static :
        left  : [ 100, 150 ]
        right : [ 160, 210 ]
        color : "ffffaa"

    - static :
        left  : [ 10, 130 ]
        right : [ 80, 190 ]
        color : "ffffbb"
